### ISSUE TITLE
Max hit calculating on equip, not prayer turn on. 

### ISSUE THREAD

**Issue by densep** [j-cob44/max-hit-calc#15]
The Max hit does not auto update on prayer turn on. Example scenario. With Whip equipped Max hit shows 29, actual is 29 When you turn on piety Max hit reads 29, actual is 35. In order to show proper max hit, you must change weapons with the prayer on. 

Ideally, max hit should recalculate on prayer turn on. Not on equip.

**Comment by j-cob44** [comment]
Hey @densep! Can you confirm what version you are on by checking what version shows up in the plugin hub of RuneLite?

**Comment by j-cob44** [comment]
I've discovered the problem, and this seems to only occur when you install the plugin while already logged into the game. Once you log out and log back in this will be fixed as the plugin fully starts up on login. 

I'll be fixing this for in next patch, thanks for spotting this!
