### ISSUE TITLE
Max hit calculation missing Ruinous Prayers from Leagues 4

### ISSUE THREAD

**Issue by tehdankbox** [j-cob44/max-hit-calc#19]
There's a couple of different prayers in the prayer book affecting melee/ranged/magic strength, and they're currently not calculated.

This gear (Trident, 99 Magic, Tormented Bracelet) can hit a 36 using Vaporise (4% Magic Damage prayer) with the Mage relic as an example.
![image](https://github.com/j-cob44/max-hit-calc/assets/51785839/a0b250f4-dbcd-4f96-b5c9-67c665414512)

**Comment by j-cob44** [comment]
Hey, thank you for letting me know about this! I'll get to updating this over the weekend and I'll post progress updates here. 

Happy Thanksgiving!

**Comment by j-cob44** [comment]
Just a quick update, I have to wait for the next runelite update. The next update includes the variables for all ruinous powers prayers. As soon as runelite is updated, I can update the calculator.

**Comment by j-cob44** [comment]
Was able to hardcode the prayer calculations in v1.10.1 (#20). Just needs to be approved by Runelite admins, https://github.com/runelite/plugin-hub/pull/5242. Won't be much longer now!

**Comment by j-cob44** [comment]
Hey @tehdankbox, the update went live last night! Could you verify you are on version 1.10.1 and that the ruinous powers are now calculating for you?

**Comment by tehdankbox** [comment]
Hey @j-cob44, the plugin is on 1.10.1 and the ruinous powers are now calculating, but only seem to update once you change equipment while already having an active prayer, and doesn't seem to work for magic spells/weapons.

**Comment by j-cob44** [comment]
Hi @tehdankbox, a fix was pushed today for that issue. The calculation should now update whenever a ruinous prayer is activated/deactivated. Please let me know if it is working for you on v1.10.2. Thanks!
