### ISSUE TITLE
New mage bonus values need updating

### ISSUE THREAD

**Issue by SamuelDev** [j-cob44/max-hit-calc#33]
From [today's blog](https://secure.runescape.com/m=news/a=13/project-rebalance-combat-changes?oldschool=1):

- Occult Necklace: Magic damage reduced from 10% to 5%.
- Ancestral Robes set pieces: Magic damage per piece increased from 2% to 3%.
- Virtus Robes set pieces: Magic damage per piece increased from 1% to 2%.
- The following items have had their Magic damage per piece increased from 0 to 1%:
  - Infinity Robes.
  - Dagon'hai Robes.
  - 3rd Age Mage Armour.
  - Ahrim's Robes.
  - Blue Moon Armour.
  - Elder Chaos Druid Robes.
  - Bloodbark Armour.
- Augury: Magic damage while active increased from 0 to 4%.
  - Note: Tumeken's Shadow doesn't multiply accuracy or damage bonuses gained from Prayers, so this would remain a 4% increase rather than 12% when using the Shadow.
- Mystic Might: Magic damage while active increased from 0 to 2%.
- Mystic Lore: Magic damage while active increased from 0 to 1%.
- Eternal Boots: Magic damage increased from 0 to 1%.
- Mage's Book: Magic damage increased from 0 to 2%.
- Ancient Wyvern Shield: Magic damage increased from 0 to 2%.
- Malediction Ward: Magic damage increased from 0 to 2%.
- Arcane Spirit Shield: Magic damage increased from 0 to 3%.
- Seers' Ring and Seers' Ring (i): Magic damage increased from 0 to 0.5%
- Elite Void Mage Set bonus: Magic damage increased from 2.5% to 5%.

Tomes also changed from 50% to 10%.

Also there was a new item added that reduces magic damage by 80% `Added a 'Cursed Amulet of Magic' drop at a rate of 1/5 from the Necromancer south of Shayzien. This amulet provides -80% Magic Damage, useful for some niche scenarios where you might want to keep your damage numbers as low as possible!`

I did some testing with trident and it appears to not work currently. It says my max hit is 26 without any gear on. I put on my god cape and 2 pieces of bloodbark for a 4% increase. 26*1.04=27.04 but my max hit still reads as 26.

**Comment by j-cob44** [comment]
Hi @SamuelDev! Work is underway on all of these changes. All of the item stat value changes come from Runelite themselves and will automatically be fixed once it is fixed within Runelite.

Currently, I am working on the new bonuses from prayers, set bonuses, and to the standard spell book spells base hits. I hope to have this all done by today.

**Comment by j-cob44** [comment]
Hello again,
The initial changes have been pushed in (#34). Next, they need to be approved by Runelite (https://github.com/runelite/plugin-hub/pull/6108). 

I'm not sure when the Item Stats will be corrected to the new values, but when they are, this plugin will immediately work with them and be up to date. Usually, they are pretty quick about fixing them when they are changed.

**Comment by j-cob44** [comment]
Hi,
Earlier today, the new wiki values were updated by Runelite so all item stats should be current and used correctly in the plugin. Next, the Runelite team has to review this plugins changes and accept them for any updated set bonuses and mage prayer bonuses to work correct from last weeks update. Hopefully it will be accepted soon.

**Comment by j-cob44** [comment]
Hi @SamuelDev,
The plugin has been updated in Runelite today, please restart your client to update. Let me know if you find any problems with this version!
