### ISSUE TITLE
Max hit not working for Mystic Mith Staff + Black Demons + Water Spells

### ISSUE THREAD

**Issue by Simpuhl** [j-cob44/max-hit-calc#36]
I am hitting 26s and it says max hit is only 18

Not sure if this was updated to account for the +40% water dmg to black demons?

**Comment by j-cob44** [comment]
Hi! Yes, any boosts that are from the new type weaknesses are unaccounted for right now.

I'm looking to make this a feature in the future but I just haven't had the time recently.

**Comment by Simpuhl** [comment]
Ah ok, I wonder if you could do some sort of data grab off the wiki to get all the details

**Comment by j-cob44** [comment]
Yeah, my hope would be to make it so the plugin knew what enemy you were currently attacking to be able to retrieve that info from the wiki. 

If that info isn't available from the wiki, then I would have to store it in the plugin which is doable as well, but would require the plugin to be updated with future content. 

I'd like to future proof it as much as possible.

**Comment by Simpuhl** [comment]
I believe just relying on the wiki if that's possible, does it grab via API? Wonder if there's a limit

**Comment by j-cob44** [comment]
Runelite usually scrapes the wiki a few days after an update and stores that for all plugins to use without needing to call the wikis at all. That's how this plugin gets all the information about weapon stats. It would depend on if the npc type weakness info is available in that. When they first introduced the type bonuses, it wasn't, but I haven't checked again yet.

**Comment by j-cob44** [comment]
I've decided to include this as part of my v2.0.0 rework. I've also decided to just make my own data as I didn't see an easily exposed way to get the weakness information.

Currently, I've got it working immediately when you click on an enemy that has a type bonus, it will recalculate and give you your new max hit against that enemy. I'm working on making this expire after a certain amount of time of having not clicked on an enemy. So far, looks good and I hope to have it out soon.

**Comment by Simpuhl** [comment]
Hell yeah, will the current one update it it automatically once you upload it and its approved or is it going to be an entire new add on?

**Comment by j-cob44** [comment]
Same plugin, it will update automatically when approved by Runelite.

**Comment by j-cob44** [comment]
This closed when I pushed my changes to the plugin, but it will actually close when the changes are accepted by Runelite. You can follow its progress here, https://github.com/runelite/plugin-hub/pull/6637.

**Comment by Simpuhl** [comment]
Ty brother.

**Comment by j-cob44** [comment]
Hey this just got merged into Runelite's Hub. If you're still on the old version, please restart Runelite and it should automatically update for you.

If you run into any issues at all, please make a new issue and let me know about it. I was the only one testing this time so I'm sure there is stuff I missed. The Runelite reviewers already found some stuff that I'll be fixing in a couple of days.

**Comment by Simpuhl** [comment]
Thank you sir, I'll report anything I find. Appreciate it
