### ISSUE TITLE
Max hit doesn't take into account invisble bonus from combat style

### ISSUE THREAD

**Issue by billionai** [j-cob44/max-hit-calc#4]
I am exactly on a point where depending on the combat style, I get 1 extra max hit. My current setup is: 30 strength, adamant mace.

When I use the accurate, controlled or defensive style, my max hit is (correctly) reported as 5. However, because of the invisible +3 boost to strength with the aggressive style, my max hit becomes 6, and the plugin does not change. I imagine that the same bug would happen if I was 32 strength and using the controlled style, but I having gotten there yet to verify :p

**Comment by billionai** [comment]
it ends with the decimal. I'll check my max hit without equipments in a moment, once I'm done with work

**Comment by j-cob44** [comment]
Gotcha! So the decimal ending version is not my plugin, that plugin is called Max Hit by Matt 12 year. My version is called Max Hit Calculator, check it out on the plugin hub! My version fixes all of those small calculation inaccuracies.

**Comment by billionai** [comment]
Ah alright. Sorry about the bogus bug report then

**Comment by j-cob44** [comment]
No worries! Check out my plugin and let me know what you think. The style bonus will show on it!
