### ISSUE TITLE
Plugin doesn't take golembane when calculating max hit

### ISSUE THREAD

**Issue by billionai** [j-cob44/max-hit-calc#6]
When I equip a Barronite Mace (currently only weapon with the golembane[1] attribute), there is no section saying "max attack against type" like it does when using the Silverlight, for instance. It should give a 15% strength bonus when fighting golems

[1] https://oldschool.runescape.wiki/w/Golem_(attribute)

Also, hi :3 I started using your version and it works great!! Thanks for working on it!

**Comment by j-cob44** [comment]
Hey Billion! Glad it's working great for you!

I didn't know about the golem attribute so thank you for bringing it to my attention! I'm going to work on it and it will be in the next patch (v1.1.3)

**Comment by j-cob44** [comment]
Update is pushed! Will be released when pushed to the plugin hub (https://github.com/runelite/plugin-hub/pull/4479)

Thanks again for the report!
